---
#=============================================== Local  Env ==============================================
spring:
    profiles: local

info:
    component: Zuul Server

server:
    port: 8765

  
endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

#important part
zuul:
    routes:
        stores: /stores/**
        customers: /customers/**
        zuulserver: /self/**
        
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    
#eureka configuration
eureka:
    client:
        serviceUrl:
            defaultZones: ${EUREKA_SERVER_URL:http://localhost:8761/eureka} 
