server:
    port: 8761

eureka:
    instance:
        hostname: eureka_1
    server:
        waitTimeInMsWhenSyncEmpty: 0
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZones: "http://localhost:8762/eureka"