#==========================================Local Env ====================================
---
spring: 
    profiles: local

server:
    port: 8761

#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，
#所以我们需要禁用它的客户端注册行为。(如果你要开启这个配置，你需要启动至少两个eurekaserver
#让他们互相注册)
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        hostname: eureka_local
---
#===========================================Dev_Peer_1 Env ===============================
spring:
    profiles: dev_peer_1
server: 
    port: 8761

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8762/eureka
    server:
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        hostname: eureka_dev_peer_1
        # 每隔10给eureka server 发送一次心跳
        lease-renewal-interval-in-seconds: 10
        

---
#============================================Dev_Peer_2 Env =================================
spring:
    profiles: dev_peer_2

server:
    port: 8762

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    server:
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        hostname: eureka_dev_peer_2 
        # 每隔10给eureka server 发送一次心跳
        lease-renewal-interval-in-seconds: 10    


    
        
    
        
