server:
    port: 8888

management:
    context-path: /admin
    security:
        enabled: false
  
logging:
    level:
        com.netflix.discovery: 'OFF'
        org.springframework.cloud: 'DEBUG'