server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG

# http basic authentication    
security:
  user:
    name: user
    password: password
    

# spring session implements by redis
spring:
  redis:
    host: localhost
    password:
    port: 6379   