server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG

spring:
  thymeleaf:
    cache: false

# http basic authentication    
security:
  user:
    name: user
    password: password